version: '3'
name: asbemulator-suite
services:
  rabbitmq:
    image: rabbitmq:3.12-management
    environment:
      RABBITMQ_NODE_PORT: 5688
    ports:
      - "5688:5688"
    healthcheck:
      test: ["CMD-SHELL", "if rabbitmqctl status; then \nexit 0 \nfi \nexit 1"]
      interval: 5s
      timeout: 10s
      start_period: 5s
      retries: 10
  asbemulator:
    build: .
    environment:
      HOST: 0.0.0.0
    ports:
      - "4444:4444"
    depends_on:
      rabbitmq: 
        condition: service_healthy
    links:
      - rabbitmq
  amqpgateway:
    ports:
      - "5671:5671"
    environment:
      HOST: 0.0.0.0
    build: 
      context: .
      dockerfile: Dockerfile.gateway
    depends_on:
      - asbemulator
    links:
      - asbemulator